import React from 'react'
import '../../reset.css'
import './square.css'

class Square extends React.Component {
	constructor(props) {
		super(props)
		this.position = this.props.position;																															// a 2d array like [0,0] generated by the Board components render loop 
		this.handleClick = this.handleClick.bind(this)
		this.drop = this.drop.bind(this)
	}

	handleClick(e) {
		this.props.handleClick(this.props.position[0],this.props.position[1])													// this passes the Game component's playMove method the value of the caller which mutates this.props.playerBoard
		if (this.props.board.playerBoard[this.position[0]][this.position[1]] === 'B') {										// Checks the board to see if it was a bomb
			alert('BOOM!!!')
		}
	}

	allowDrop(e) {
		e.preventDefault()
	}

	drop(e) {
		this.props.handleDrop(e,this.position)
	}

						// below we render a button with a value equal to its index that will be recalled on click. Button will display content at the index of playerBoard
	render() {
		this.style = {height: '10vh'};
		let content = this.props.board.playerBoard[this.position[0]][this.position[1]]


		return (
		  <div className='square' 
		  	onClick={this.handleClick} 
				onDragOver={this.allowDrop}
				onDrop={this.drop}
				style={this.style}
				id = {this.position}
			>
		  </div>
		)
	}
}

export default Square